image: alpine

stages:
  - testing
  - production

variables:
  GN_GITLAB_TESTING_URL: "gitlab.interno.gerencianet.com.br"
  GIT_SSL_NO_VERIFY: "true"

before_script:
  - apk update && apk add --update grep bash zip py-pip git openssh curl && rm -rf /var/cache/apk/*
  - pip install --upgrade pip
  - pip install -Iv urllib3==1.22 --user
  - pip install awscli

Deploy em Teste:
  stage: testing
  allow_failure: false
  script:
    - aws s3 cp --acl public-read --storage-class INTELLIGENT_TIERING --exclude "*.svg" --recursive ./gn-documentacao/build/doc-gerencianet/ s3://pre-dev.testegerencianet.com.br/
    - aws s3 cp --acl public-read --storage-class INTELLIGENT_TIERING --exclude "*" --include "*.svg" --metadata-directive REPLACE --content-type image/svg+xml --recursive ./gn-documentacao/build/doc-gerencianet/ s3://pre-dev.testegerencianet.com.br/
  only:
    - master

Deploy em Producao:
  stage: production
  allow_failure: false
  script:
    - aws s3 cp --acl public-read --storage-class INTELLIGENT_TIERING --exclude "*.svg" --recursive ./gn-documentacao/build/doc-gerencianet/ s3://pre-dev.gerencianet.com.br/
    - aws s3 cp --acl public-read --storage-class INTELLIGENT_TIERING --exclude "*" --include "*.svg" --metadata-directive REPLACE --content-type image/svg+xml --recursive ./gn-documentacao/build/doc-gerencianet/ s3://pre-dev.gerencianet.com.br/
  only:
    - master
  when: manual
